export default [
    'Cuillère',
    'Sèche-cheveux',
    'Oreille',
    'Cri d\'effroi',
    'Somnambule',
    'Inondation',
    'Boire',
    'Faire une prédiction',
    'Lit',
    'Lune',
    'PQ',
    'Déguisée / Déguisé',
    'Vomir',
    'Aspirer',
    'Licorne',
    'Caleçon',
    'Ascenseur',
    'Kebab',
    'Faire un câlin',
    'Dragon',
    'À quatre pattes',
    'Bouché',
    'S\'inscrire sur un site de rencontres',
    'Aveuglée / Aveuglé',
    'Coupure de courant',
    'SMS',
    'Cadeau',
    'Route',
    'Complot',
    'Main',
    'Chanter',
    'Chaussure',
    'Se souvenir',
    'Frapper de toutes ses forces',
    'Fromage',
    'Mur',
    'Élastique',
    'Télévision',
    'Avoir froid',
    'Dinosaure',
    'Clé',
    'Couteau',
    'Dent',
    'Robot',
    'Sonner à la porte',
    'Chocolat',
    'Plombière / Plombier',
    'Sac à dos',
    'Crocodile',
    'Tomber dans les escaliers',
    'Paniquer',
    'Ventre',
    'Jus d\'orange',
    'Ordinateur',
    'Droguée / Drogué',
    'Canard',
    'Une heure',
    'Enfermée / Enfermé',
    'Tête',
    'Super pouvoir',
    'Voisine / Voisin',
    'Douche',
    'Faire un bisou',
    'Clin d\'oeil',
    'Invisible',
    'Fin du monde',
    'Fatiguée / Fatigué',
    'Masquée / Masqué',
    'Jour de l\'an',
    'Télécommande',
    'Ombre',
    'Livre',
    'Se déshabiller',
    'Danser',
    'Oublier',
    'Cheville',
    'Tourner sans fin',
    'Chapeau',
    'Dévorer',
    'Cheveux',
    'Jus de raisin',
    'Ventriloque',
    'Totalement ivre',
    'Chambre',
    'Banane',
    'Manteau',
    'Symboles étranges',
    'Arc en ciel',
    'Pluie',
    'Alarme',
    'Pantalon',
    'Se réveiller',
    'Lunettes',
    'Vers 4h du matin',
    'Pleurer',
    'Céréales',
    'Chaise',
    'Désespérée / Désespéré',
    'Glace',
    'Odeur désagréable',
    'Yeux',
    'Chaussette',
    'Prendre une photo',
    'Sauter à pieds joints',
    'Maison',
    'Pyjama',
    'Fou',
    'Nez',
    'Musique épique',
    'Trou',
    'Radio-réveil',
    'Petit-déjeuner',
    'S\'offusquer',
    'Porte',
    'Fenêtre',
    'Un quart d\'heure',
    'Anniversaire',
    'Très très lentement',
    'S\'excuser',
    'Prendre son courage à deux mains',
    'Godzilla',
    'Visage',
    'Empoisonner',
    'Téléphone',
    'Thunes',
    'Pomme',
    'Parler',
    'Trouver un truc',
    'Cave',
    'Entrer par effraction',
    'Exploser',
    'Skateboard',
    'Faire un diagnostic',
    'Rivière',
    'Tronçonneuse',
    'Neige',
    'Plante carnivore',
    'Pelle',
    'Tournage de film',
    'Igloo',
    'Une autre dimension',
    'Chevaucher',
    'Lampadaire',
    'Mort-vivante / Morte-vivant',
    'Bébé',
    'Magicienne / Magicienn',
    'Cagoule',
    'Aéroport',
    'Restaurant',
    'Bateau',
    'Voleuse / Voleur',
    'Bus',
    'Courir très vite',
    'Ver de terre',
    'Etoiles',
    'Ruelle sombre',
    'Parc',
    'Lego',
    'Hurler à la lune',
    'Ski',
    'Océan',
    'Nager',
    'Poule',
    'Hasard',
    'Montagne',
    'Trottinette',
    'Chien',
    'Pirate',
    'Grenade',
    'Policière / Policier',
    'Deltaplane',
    'Vente aux enchères',
    'Vache',
    'Ninja',
    'Avion',
    'Bombe nucléaire',
    'Bonhomme de neige',
    'Docteure / Docteur',
    'Rêve',
    'Vent',
    'Alien',
    'Se perdre',
    'Prophétie',
    'Grève des transports',
    'Brouillard',
    'Limite',
    'Tracteur',
    'Prison',
    'Planche à voile',
    'Bibliothèque',
    'Embuscade',
    'Vélo',
    'Voiture en panne',
    'Lacets défaits',
    'Mars',
    'Retour en arrière',
    'Armée de rats',
    'Ambulance',
    'Tournoi',
    'Dentiste',
    'Viking',
    'Épée',
    'Cochon',
    'Hôpital',
    'Mort',
    'Désert',
    'Au moins mille ans',
    'Faire demi-tour',
    'Cirque',
    'Barbecue',
    'Ballon',
    'Tortue',
    'Agent secrète / Agente secret',
    'Parsemé de pétales de roses',
    'Zoo',
    'Égouts',
    'Forêt',
    'Caillou dans la chaussure',
    'Rendez-vous',
    'La semaine dernière',
    'Bonnet en laine',
    'Météorite',
    'Fusée',
    'Cheval',
    'Incendie',
    'Feu rouge',
    'Fête foraine',
    'Loup-Garou',
    'Espace',
    'Vortex',
    'Détective privée / Détective privé',
    'Chat',
    'Chantier',
    'Sous hypnose',
    'Accident',
    'Lumière étrange',
    'Tremblement de terre',
    'Squelette',
    'Malette',
    'Pompière / Pompier',
    'Voyageur du temps || Voyageuse du temps',
    'Plage',
    'Vaisseau spatial',
    'Tempète',
    'Supermarché',
    'Boussole',
    'En lévitation',
    'Verglas',
    'Taxi',
    'Manoir hanté',
    'Marteau',
    'Venger',
    'Trompette',
    'Montgolfière',
    'Passage piéton',
    'Maudite / Maudit',
    'Ours polaire',
    'Minuscule',
    'Hibou',
    'Feu d\'artifice',
    'Soleil',
    'Champignon',
    'Hier matin',
    'Camion',
    'Train',
    'Vampire',
    'Jambe cassée',
    'Jardin',
    'Fouet',
    'Glisser',
    'Arbre',
    'Clé à molette',
    'Menottes',
    'Halloween',
    'Noël',
    'S\'enfuir',
    'Sexe',
    'Pièce secrète',
    'Mécanisme caché',
]